# Generated by Django 6.0.4 on 2026-06-24 11:52

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admanager', '0002_admanager_verification_requested_and_more'),
        ('advertiser', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdManagerSubaccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subaccount_code', models.CharField(max_length=120, unique=True)),
                ('business_name', models.CharField(max_length=180, null=True)),
                ('bank_name', models.CharField(max_length=120)),
                ('bank_code', models.CharField(max_length=10)),
                ('account_number_last4', models.CharField(max_length=4, null=True)),
                ('account_name', models.CharField(max_length=180)),
                ('settlement_bank', models.CharField(blank=True, max_length=120)),
                ('is_active', models.BooleanField(default=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('gateway_response', models.JSONField(blank=True, default=dict)),
                ('ad_manager', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='paystack_subaccount', to='admanager.admanager')),
            ],
        ),
        migrations.CreateModel(
            name='AdManagerSubaccountAuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.CharField(choices=[('created', 'Created'), ('bank_details_changed', 'Bank Details Changed'), ('deactivated', 'Deactivated'), ('reactivated', 'Reactivated'), ('verified', 'Verified')], max_length=32)),
                ('note', models.TextField(blank=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subaccount_audit_logs', to=settings.AUTH_USER_MODEL)),
                ('subaccount', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='audit_logs', to='payments.admanagersubaccount')),
            ],
        ),
        migrations.CreateModel(
            name='CampaignPayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('platform_fee', models.DecimalField(decimal_places=2, max_digits=12)),
                ('manager_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=12)),
                ('reference', models.CharField(max_length=120, unique=True)),
                ('paystack_reference', models.CharField(blank=True, max_length=120)),
                ('gateway_response', models.JSONField(blank=True, default=dict)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('refunded_at', models.DateTimeField(blank=True, null=True)),
                ('refund_reference', models.CharField(blank=True, max_length=120)),
                ('campaign', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='payment', to='advertiser.campaign')),
                ('subaccount', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='campaign_payments', to='payments.admanagersubaccount')),
            ],
        ),
        migrations.CreateModel(
            name='AdManagerEarning',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('platform_fee', models.DecimalField(decimal_places=2, max_digits=12)),
                ('paystack_reference', models.CharField(blank=True, max_length=120)),
                ('earned_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ad_manager', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='earnings', to='admanager.admanager')),
                ('subaccount', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='earnings', to='payments.admanagersubaccount')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='manager_earnings', to='payments.campaignpayment')),
            ],
        ),
        migrations.CreateModel(
            name='PayoutRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bank_name', models.CharField(max_length=120)),
                ('account_number_last4', models.CharField(max_length=4)),
                ('account_name', models.CharField(max_length=180)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('paystack_transfer_code', models.CharField(blank=True, max_length=120, null=True, unique=True)),
                ('paystack_reference', models.CharField(blank=True, max_length=120)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed'), ('reversed', 'Reversed')], default='pending', max_length=12)),
                ('gateway_response', models.JSONField(blank=True, default=dict)),
                ('is_flagged', models.BooleanField(default=False)),
                ('flag_reason', models.TextField(blank=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('ad_manager', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payout_records', to='admanager.admanager')),
                ('subaccount', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payout_records', to='payments.admanagersubaccount')),
            ],
        ),
        migrations.AddIndex(
            model_name='admanagersubaccount',
            index=models.Index(fields=['is_active'], name='payments_ad_is_acti_a9f332_idx'),
        ),
        migrations.AddIndex(
            model_name='admanagersubaccount',
            index=models.Index(fields=['subaccount_code'], name='payments_ad_subacco_e35b81_idx'),
        ),
        migrations.AddIndex(
            model_name='admanagersubaccountauditlog',
            index=models.Index(fields=['subaccount', 'created_at'], name='payments_ad_subacco_c2c6bb_idx'),
        ),
        migrations.AddIndex(
            model_name='admanagersubaccountauditlog',
            index=models.Index(fields=['event'], name='payments_ad_event_19758d_idx'),
        ),
        migrations.AddIndex(
            model_name='campaignpayment',
            index=models.Index(fields=['status'], name='payments_ca_status_d70018_idx'),
        ),
        migrations.AddIndex(
            model_name='campaignpayment',
            index=models.Index(fields=['reference'], name='payments_ca_referen_692ed5_idx'),
        ),
        migrations.AddIndex(
            model_name='campaignpayment',
            index=models.Index(fields=['paystack_reference'], name='payments_ca_paystac_579ecf_idx'),
        ),
        migrations.AddConstraint(
            model_name='campaignpayment',
            constraint=models.CheckConstraint(condition=models.Q(('total_amount__gt', 0)), name='campaign_payment_total_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='campaignpayment',
            constraint=models.CheckConstraint(condition=models.Q(('platform_fee__gte', 0)), name='campaign_payment_platform_fee_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='campaignpayment',
            constraint=models.CheckConstraint(condition=models.Q(('manager_amount__gt', 0)), name='campaign_payment_manager_amount_positive'),
        ),
        migrations.AddIndex(
            model_name='admanagerearning',
            index=models.Index(fields=['ad_manager', 'earned_at'], name='payments_ad_ad_mana_c2f4a3_idx'),
        ),
        migrations.AddIndex(
            model_name='admanagerearning',
            index=models.Index(fields=['paystack_reference'], name='payments_ad_paystac_501ad0_idx'),
        ),
        migrations.AddConstraint(
            model_name='admanagerearning',
            constraint=models.UniqueConstraint(fields=('payment', 'ad_manager'), name='unique_manager_earning_per_payment'),
        ),
        migrations.AddConstraint(
            model_name='admanagerearning',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='earning_amount_positive'),
        ),
        migrations.AddIndex(
            model_name='payoutrecord',
            index=models.Index(fields=['ad_manager', 'status'], name='payments_pa_ad_mana_fd7787_idx'),
        ),
        migrations.AddIndex(
            model_name='payoutrecord',
            index=models.Index(fields=['status'], name='payments_pa_status_cc8e2e_idx'),
        ),
        migrations.AddIndex(
            model_name='payoutrecord',
            index=models.Index(fields=['is_flagged'], name='payments_pa_is_flag_26ef2d_idx'),
        ),
        migrations.AddIndex(
            model_name='payoutrecord',
            index=models.Index(fields=['paystack_transfer_code'], name='payments_pa_paystac_02a961_idx'),
        ),
        migrations.AddConstraint(
            model_name='payoutrecord',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='payout_amount_positive'),
        ),
    ]
