# Generated by Django 6.0.4 on 2026-07-16 01:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admanager', '0002_alter_admanager_commission_rate'),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admanagersubaccount',
            name='ad_manager',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='paystack_subaccount', to='admanager.admanager'),
        ),
    ]
