# Generated by Django 6.0.4 on 2026-06-20 04:44

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('advertiser', '0001_initial'),
        ('device', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillboardCapacity',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('max_slots_per_day', models.PositiveIntegerField(default=0)),
                ('slot_duration_seconds', models.PositiveBigIntegerField(default=30)),
                ('last_calculated_at', models.DateTimeField(auto_now=True)),
                ('billboard', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='capacity', to='device.billboard')),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ScheduleGenerationLog',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('result', models.CharField(choices=[('success', 'Success'), ('partial', 'Partial (some dates had no capacity)'), ('failed', 'Failed')], max_length=20)),
                ('slots_created', models.PositiveIntegerField(default=0)),
                ('slots_skipped', models.PositiveIntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_logs', to='advertiser.campaignslot')),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(db_index=True)),
                ('play_order', models.PositiveIntegerField()),
                ('duration_seconds', models.PositiveIntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('billboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_slots', to='device.billboard')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_slots', to='advertiser.campaign')),
                ('campaign_slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_slots', to='advertiser.campaignslot')),
            ],
            options={
                'indexes': [models.Index(fields=['billboard', 'date', 'is_active'], name='scheduling__billboa_3a422d_idx'), models.Index(fields=['campaign', 'date'], name='scheduling__campaig_1c3b81_idx'), models.Index(fields=['date'], name='scheduling__date_b01588_idx')],
                'unique_together': {('billboard', 'date', 'play_order')},
            },
        ),
    ]
