# Generated by Django 6.0.4 on 2026-06-20 17:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertiser', '0001_initial'),
        ('scheduling', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedulegenerationlog',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_logs', to='advertiser.campaign'),
        ),
    ]
