# Generated by Django 6.0.4 on 2026-08-23 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertiser', '0009_alter_media_duration_seconds'),
        ('device', '0002_playbacklog_time_slot'),
        ('scheduling', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='timeslot',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='timeslot',
            name='scheduled_time',
            field=models.TimeField(blank=True, db_index=True, help_text=" The real clock time this exact play is scheduled for what the device actually checks against, not jst an ordering position. An advertiser's 7am - 9am window only ever gets seats whose scheduled_time actually falls in 7am-9am", null=True),
        ),
        migrations.AlterUniqueTogether(
            name='timeslot',
            unique_together={('billboard', 'date', 'scheduled_time')},
        ),
        migrations.AddIndex(
            model_name='timeslot',
            index=models.Index(fields=['campaign', 'date', 'scheduled_time'], name='scheduling__campaig_9ab786_idx'),
        ),
    ]
