# Generated by Django 6.0.4 on 2026-08-26 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertiser', '0009_alter_media_duration_seconds'),
        ('device', '0002_playbacklog_time_slot'),
        ('scheduling', '0002_alter_timeslot_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='timeslot',
            name='scheduling__campaig_9ab786_idx',
        ),
        migrations.AlterUniqueTogether(
            name='timeslot',
            unique_together={('billboard', 'date', 'play_order')},
        ),
        migrations.AddField(
            model_name='billboardcapacity',
            name='max_concurrent_positions',
            field=models.PositiveIntegerField(default=8, help_text='How many advertiser positions can share the rotation loop at once, for any given daypart, before this billboard is sold out.'),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='scheduled_time',
            field=models.TimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddIndex(
            model_name='timeslot',
            index=models.Index(fields=['billboard', 'date', 'play_order'], name='scheduling__billboa_25f152_idx'),
        ),
    ]
