# Generated by Django 6.0.4 on 2026-09-01 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0003_remove_timeslot_scheduling__campaig_9ab786_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billboardcapacity',
            name='max_concurrent_positions',
            field=models.PositiveIntegerField(default=8, help_text="Total number of rotation-loop positions this billboard sells for any given daypart, before it's sold out. This is a shared pool, not a per-advertiser count — one advertiser's Ad Slots Per Day claims that many positions from this same total, so a single advertiser CAN buy the entire capacity (a full buyout), leaving none for anyone else."),
        ),
    ]
