# Generated by Django 6.0.4 on 2026-06-20 17:15

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RevenueSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_percentage', models.DecimalField(decimal_places=2, default=Decimal('30.00'), max_digits=5)),
                ('admanager_percentage', models.DecimalField(decimal_places=2, default=Decimal('70.00'), max_digits=5)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
