# Generated by Django 6.0.4 on 2026-05-14 07:46

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admanager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device_uid', models.CharField(max_length=80, unique=True)),
                ('auth_token', models.CharField(editable=False, max_length=96, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('location_name', models.CharField(max_length=255)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('screen_width_px', models.PositiveIntegerField(default=1920)),
                ('screen_height_px', models.PositiveIntegerField(default=1080)),
                ('price_per_slot', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('offline', 'Offline'), ('disabled', 'Disabled')], default='pending', max_length=24)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('firmware_version', models.CharField(blank=True, max_length=80)),
                ('ad_manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='admanager.admanager')),
            ],
            options={
                'indexes': [models.Index(fields=['device_uid'], name='device_devi_device__5322d4_idx'), models.Index(fields=['status'], name='device_devi_status_db0e43_idx'), models.Index(fields=['last_seen_at'], name='device_devi_last_se_470b03_idx')],
            },
        ),
    ]
