# Generated by Django 6.0.4 on 2026-05-24 22:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admanager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Billboard',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('location_name', models.CharField(max_length=255)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('screen_type', models.CharField(choices=[('led', 'LED'), ('lcd', 'LCD'), ('digital', 'Digital'), ('static', 'Static')], default='led', max_length=24)),
                ('screen_width_px', models.PositiveIntegerField(default=1920)),
                ('screen_height_px', models.PositiveIntegerField(default=1080)),
                ('price_per_slot', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('operating_hours_start', models.TimeField(default='06:00')),
                ('operating_hours_end', models.TimeField(default='22:00')),
                ('availability', models.CharField(choices=[('available', 'Available'), ('unavailable', 'Unavailable'), ('maintenance', 'Under Maintenance')], default='available', max_length=24)),
                ('ad_manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billboards', to='admanager.admanager')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerDevice',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pairing_code', models.CharField(blank=True, max_length=12, unique=True)),
                ('auth_token', models.CharField(editable=False, max_length=96, unique=True)),
                ('device_uid', models.CharField(max_length=80, unique=True)),
                ('firmware_version', models.CharField(blank=True, max_length=80)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('offline', 'Offline'), ('disabled', 'Disabled')], default='pending', max_length=24)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('token_claimed_at', models.DateTimeField(blank=True, null=True)),
                ('billboard', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='player_device', to='device.billboard')),
            ],
        ),
        migrations.AddIndex(
            model_name='billboard',
            index=models.Index(fields=['ad_manager'], name='device_bill_ad_mana_f9a1b7_idx'),
        ),
        migrations.AddIndex(
            model_name='billboard',
            index=models.Index(fields=['availability'], name='device_bill_availab_c4e2ed_idx'),
        ),
        migrations.AddIndex(
            model_name='playerdevice',
            index=models.Index(fields=['device_uid'], name='device_play_device__7c1fa6_idx'),
        ),
        migrations.AddIndex(
            model_name='playerdevice',
            index=models.Index(fields=['status'], name='device_play_status_71e2c4_idx'),
        ),
        migrations.AddIndex(
            model_name='playerdevice',
            index=models.Index(fields=['last_seen_at'], name='device_play_last_se_020647_idx'),
        ),
        migrations.AddIndex(
            model_name='playerdevice',
            index=models.Index(fields=['pairing_code'], name='device_play_pairing_761df6_idx'),
        ),
    ]
