# Generated by Django 6.0.4 on 2026-07-25 18:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0001_initial'),
        ('scheduling', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='playbacklog',
            name='time_slot',
            field=models.ForeignKey(blank=True, help_text='The scheduled slot this play fulfilled, if it matched one.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='playback_logs', to='scheduling.timeslot'),
        ),
    ]
