# Generated by Django 6.0.4 on 2026-06-13 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='billboard',
            name='media_file',
            field=models.FileField(blank=True, help_text="Upload an image or video representing this billboard's physical state.", null=True, upload_to='billboards/media/'),
        ),
    ]
