# Generated by Django 6.0.4 on 2026-06-20 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billboard',
            name='screen_type',
            field=models.CharField(choices=[('led', 'LED'), ('lcd', 'LCD'), ('digital', 'Digital')], default='led', max_length=24),
        ),
    ]
