# Generated by Django 6.0.4 on 2026-06-12 15:46

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceMetric',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cpu_usage_pct', models.FloatField(blank=True, null=True)),
                ('ram_usage_mb', models.PositiveIntegerField(blank=True, null=True)),
                ('free_storage_mb', models.PositiveIntegerField(blank=True, null=True)),
                ('temperature_celsius', models.FloatField(blank=True, null=True)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='device.playerdevice')),
            ],
            options={
                'indexes': [models.Index(fields=['player', 'recorded_at'], name='device_devi_player__7454d7_idx')],
            },
        ),
        migrations.CreateModel(
            name='PlaybackLog',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('media_id', models.UUIDField(db_index=True)),
                ('started_at', models.DateTimeField()),
                ('duration_seconds', models.PositiveIntegerField()),
                ('completed', models.BooleanField(default=False)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playback_logs', to='device.playerdevice')),
            ],
            options={
                'indexes': [models.Index(fields=['player', 'started_at'], name='device_play_player__677a92_idx'), models.Index(fields=['media_id'], name='device_play_media_i_c290a5_idx')],
                'constraints': [models.UniqueConstraint(fields=('player', 'media_id', 'started_at'), name='unique_playback_per_player_media_start')],
            },
        ),
    ]
