# Generated by Django 6.0.4 on 2026-08-27 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0002_playbacklog_time_slot'),
    ]

    operations = [
        migrations.AddField(
            model_name='billboard',
            name='timezone',
            field=models.CharField(choices=[('Africa/Lagos', 'Lagos (WAT, UTC+1)'), ('Africa/Accra', 'Accra (GMT, UTC+0)'), ('Africa/Nairobi', 'Nairobi (EAT, UTC+3)'), ('Africa/Johannesburg', 'Johannesburg (SAST, UTC+2)'), ('Africa/Cairo', 'Cairo (EET, UTC+2)'), ('America/New_York', 'New York (ET)'), ('America/Chicago', 'Chicago (CT)'), ('America/Los_Angeles', 'Los Angeles (PT)'), ('Europe/London', 'London (GMT/BST)'), ('Asia/Dubai', 'Dubai (GST, UTC+4)')], default='Africa/Lagos', help_text="timezone name for this billboard's physical location.", max_length=64),
        ),
    ]
