# Generated by Django 6.0.4 on 2026-06-14 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0002_billboard_media_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='billboard',
            name='country',
            field=models.CharField(blank=True, default='Nigeria', max_length=100),
        ),
        migrations.AddField(
            model_name='billboard',
            name='state',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
