# Generated by Django 6.0.4 on 2026-06-14 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0003_billboard_country_billboard_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='billboard',
            name='charge_unit',
            field=models.CharField(choices=[('hourly', 'Hourly'), ('daily', 'Daily'), ('slot', 'Per Slot')], default='slot', max_length=10),
        ),
    ]
