# Generated by Django 6.0.4 on 2026-08-30 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0003_billboard_timezone'),
    ]

    operations = [
        migrations.AddField(
            model_name='billboard',
            name='audio_enable',
            field=models.BooleanField(default=False, help_text='Only enable for indoor installs where the venue actually wants sound. Leave off for outdoor/highway billboards.'),
        ),
        migrations.AlterField(
            model_name='billboard',
            name='screen_type',
            field=models.CharField(choices=[('led', 'LED'), ('lcd', 'LCD'), ('digital', 'Digital')], default='digital', max_length=24),
        ),
    ]
