# Generated by Django 6.0.4 on 2026-08-30 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0004_billboard_audio_enable_alter_billboard_screen_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='billboard',
            old_name='audio_enable',
            new_name='audio_enabled',
        ),
    ]
