# Generated by Django 6.0.4 on 2026-06-20 04:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Admanager',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('business_name', models.CharField(max_length=200)),
                ('business_type', models.CharField(choices=[('individual', 'Individual'), ('company', 'Company')], default='individual', max_length=20)),
                ('company_registration_number', models.CharField(blank=True, max_length=100)),
                ('tax_identification_number', models.CharField(blank=True, max_length=100)),
                ('business_email', models.EmailField(max_length=254)),
                ('business_phone', models.CharField(max_length=20)),
                ('website', models.URLField(blank=True)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('country', models.CharField(default='Nigeria', max_length=100)),
                ('verification_status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected'), ('suspended', 'Suspended')], default='pending', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('suspension_reason', models.TextField(blank=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('suspended_at', models.DateTimeField(blank=True, null=True)),
                ('commission_rate', models.DecimalField(decimal_places=2, default=10.0, help_text="Platform commission percentage taken from this manager's earnings. Default 10%.", max_digits=5)),
                ('bank_name', models.CharField(blank=True, max_length=120)),
                ('account_number', models.CharField(blank=True, max_length=20)),
                ('account_name', models.CharField(blank=True, max_length=180)),
                ('bank_code', models.CharField(blank=True, help_text='Paystack bank code for transfers.', max_length=10)),
                ('recipient_code', models.CharField(blank=True, help_text='Paystack RCP code.', max_length=50, null=True, unique=True)),
                ('total_billboards', models.PositiveIntegerField(default=0)),
                ('total_campaigns_serverd', models.PositiveIntegerField(default=0)),
                ('total_impressions', models.BigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('suspended_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suspended_ad_managers', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ad_manager', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_ad_managers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ad Manager',
                'verbose_name_plural': 'Ad Managers',
                'indexes': [models.Index(fields=['verification_status'], name='admanager_a_verific_63d5fb_idx'), models.Index(fields=['is_active'], name='admanager_a_is_acti_80a1b5_idx'), models.Index(fields=['business_type'], name='admanager_a_busines_efbb48_idx'), models.Index(fields=['country', 'state', 'city'], name='admanager_a_country_e89b93_idx')],
            },
        ),
    ]
