# Generated by Django 6.0.4 on 2026-05-08 01:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Admanager',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('business_name', models.CharField(max_length=200)),
                ('business_type', models.CharField(choices=[('individual', 'Individual'), ('company', 'Company')], default='individual', max_length=20)),
                ('company_registration_number', models.CharField(blank=True, max_length=100)),
                ('tax_identification_number', models.CharField(blank=True, max_length=100)),
                ('business_email', models.EmailField(max_length=254)),
                ('business_phone', models.CharField(max_length=20)),
                ('website', models.URLField(blank=True)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('country', models.CharField(default='Nigeria', max_length=100)),
                ('verification_status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected'), ('suspended', 'Suspended')], default='pending', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('total_billboards', models.PositiveIntegerField(default=0)),
                ('total_campaigns_serverd', models.PositiveIntegerField(default=0)),
                ('total_impressions', models.BigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ad_manager', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
