# Generated by Django 6.0.4 on 2026-06-29 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admanager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admanager',
            name='commission_rate',
            field=models.DecimalField(decimal_places=2, default=30.0, help_text="Platform commission percentage taken from this manager's earnings. Default 30%.", max_digits=5),
        ),
    ]
