# Generated by Django 6.0.4 on 2026-05-20 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admanager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admanager',
            name='update_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
