# Generated by Django 6.0.4 on 2026-06-12 11:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admanager', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='admanager',
            options={'verbose_name': 'Ad Manager', 'verbose_name_plural': 'Ad Managers'},
        ),
        migrations.RenameField(
            model_name='admanager',
            old_name='update_at',
            new_name='updated_at',
        ),
        migrations.AddField(
            model_name='admanager',
            name='account_name',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name='admanager',
            name='account_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='admanager',
            name='bank_code',
            field=models.CharField(blank=True, help_text='Paystack bank code for transfers.', max_length=10),
        ),
        migrations.AddField(
            model_name='admanager',
            name='bank_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='admanager',
            name='commission_rate',
            field=models.DecimalField(decimal_places=2, default=10.0, help_text="Platform commission percentage taken from this manager's earnings. Default 10%.", max_digits=5),
        ),
        migrations.AddField(
            model_name='admanager',
            name='recipient_code',
            field=models.CharField(blank=True, help_text='Paystack RCP code.', max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='admanager',
            name='suspended_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='admanager',
            name='suspended_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suspended_ad_managers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='admanager',
            name='suspension_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='admanager',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='admanager',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_ad_managers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='admanager',
            index=models.Index(fields=['verification_status'], name='admanager_a_verific_63d5fb_idx'),
        ),
        migrations.AddIndex(
            model_name='admanager',
            index=models.Index(fields=['is_active'], name='admanager_a_is_acti_80a1b5_idx'),
        ),
        migrations.AddIndex(
            model_name='admanager',
            index=models.Index(fields=['business_type'], name='admanager_a_busines_efbb48_idx'),
        ),
        migrations.AddIndex(
            model_name='admanager',
            index=models.Index(fields=['country', 'state', 'city'], name='admanager_a_country_e89b93_idx'),
        ),
    ]
