# Generated by Django 6.0.4 on 2026-08-01 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admanager', '0002_alter_admanager_commission_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admanager',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
