# Generated by Django 6.0.4 on 2026-06-06 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admanager', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='admanager',
            name='verification_requested',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='admanager',
            name='verification_requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
