# Generated by Django 6.0.4 on 2026-06-14 17:22

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admanager', '0005_admanager_revenue_withdrawalrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bank_name', models.CharField(max_length=100)),
                ('account_name', models.CharField(max_length=200)),
                ('account_number', models.CharField(max_length=20)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ad_manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_accounts', to='admanager.admanager')),
            ],
            options={
                'ordering': ['-is_default', 'created_at'],
            },
        ),
    ]
