# Generated by Django 6.0.4 on 2026-05-25 13:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertiser',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('business_name', models.CharField(max_length=180)),
                ('business_category', models.CharField(choices=[('retail', 'Retail'), ('food_beverage', 'Food & Beverage'), ('entertainment', 'Entertainment'), ('real_estate', 'Real Estate'), ('health', 'Health & Wellness'), ('finance', 'Finance'), ('technology', 'Technology'), ('education', 'Education'), ('other', 'Other')], default='other', max_length=32)),
                ('contact_phone', models.CharField(blank=True, max_length=24)),
                ('website', models.URLField(blank=True)),
                ('address', models.TextField(blank=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='advertiser_profile', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_advertisers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
    ]
