# Generated by Django 6.0.4 on 2026-06-27 00:04

import advertiser.models
import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('device', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertiser',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50, null=True)),
                ('last_name', models.CharField(max_length=50, null=True)),
                ('business_name', models.CharField(max_length=180)),
                ('business_category', models.CharField(choices=[('retail', 'Retail'), ('food_beverage', 'Food & Beverage'), ('entertainment', 'Entertainment'), ('real_estate', 'Real Estate'), ('health', 'Health & Wellness'), ('finance', 'Finance'), ('technology', 'Technology'), ('education', 'Education'), ('other', 'Other')], default='other', max_length=32)),
                ('contact_phone', models.CharField(blank=True, max_length=24)),
                ('website', models.URLField(blank=True)),
                ('address', models.TextField(blank=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('verification_requested', models.BooleanField(default=False)),
                ('verification_requested_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='advertiser_profile', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_advertisers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('daily_start_time', models.TimeField(default='06:00')),
                ('daily_end_time', models.TimeField(default='22:00')),
                ('budget', models.DecimalField(decimal_places=2, max_digits=12)),
                ('estimated_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Calculated from billboard price_per_slot × slot count × campaign days.', max_digits=12)),
                ('actual_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('admin_split_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('admanager_split_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_admin_review', 'Pending Admin Review'), ('pending_manager_review', 'Pending Manager Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('active', 'Active'), ('paused', 'Paused'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=24)),
                ('rejection_reason', models.TextField(blank=True)),
                ('admin_reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('manager_reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('admin_reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_campaigns_admin', to=settings.AUTH_USER_MODEL)),
                ('advertiser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='advertiser.advertiser')),
                ('manager_reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_campaigns_manager', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CampaignSlot',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slots_per_day', models.PositiveIntegerField(default=1)),
                ('billboard', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='campaign_slots', to='device.billboard')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_slots', to='advertiser.campaign')),
            ],
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=180)),
                ('file', models.FileField(upload_to=advertiser.models.media_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp', 'mp4', 'mov', 'webm'])])),
                ('file_hash', models.CharField(blank=True, help_text='SHA-256 of the uploaded file. Used to detect duplicates.', max_length=64)),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video')], max_length=10)),
                ('duration_seconds', models.PositiveIntegerField(blank=True, help_text='Required for video. Duration the ad will play on screen.', null=True)),
                ('file_size_bytes', models.PositiveBigIntegerField(default=0, editable=False)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to=advertiser.models.thumbnail_upload_path)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('admin_approved', 'Admin Approved'), ('fully_approved', 'Fully Approved'), ('rejected', 'Rejected')], default='pending', max_length=16)),
                ('rejection_reason', models.TextField(blank=True)),
                ('admin_reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('manager_reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('admin_reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_media_admin', to=settings.AUTH_USER_MODEL)),
                ('advertiser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_files', to='advertiser.advertiser')),
                ('manager_reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_media_manager', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'media',
            },
        ),
        migrations.AddField(
            model_name='campaign',
            name='media',
            field=models.ForeignKey(limit_choices_to={'status': 'admin_approved'}, on_delete=django.db.models.deletion.PROTECT, related_name='campaigns', to='advertiser.media'),
        ),
        migrations.AddIndex(
            model_name='advertiser',
            index=models.Index(fields=['is_verified'], name='advertiser__is_veri_d57754_idx'),
        ),
        migrations.AddIndex(
            model_name='advertiser',
            index=models.Index(fields=['business_category'], name='advertiser__busines_2eb11f_idx'),
        ),
        migrations.AddIndex(
            model_name='campaignslot',
            index=models.Index(fields=['campaign'], name='advertiser__campaig_486350_idx'),
        ),
        migrations.AddIndex(
            model_name='campaignslot',
            index=models.Index(fields=['billboard'], name='advertiser__billboa_0a2e5a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='campaignslot',
            unique_together={('campaign', 'billboard')},
        ),
        migrations.AddIndex(
            model_name='media',
            index=models.Index(fields=['advertiser', 'status'], name='advertiser__adverti_519a6f_idx'),
        ),
        migrations.AddIndex(
            model_name='media',
            index=models.Index(fields=['media_type'], name='advertiser__media_t_177127_idx'),
        ),
        migrations.AddIndex(
            model_name='media',
            index=models.Index(fields=['status'], name='advertiser__status_392294_idx'),
        ),
        migrations.AddConstraint(
            model_name='media',
            constraint=models.UniqueConstraint(fields=('advertiser', 'file_hash'), name='unique_media_per_advertiser'),
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['advertiser', 'status'], name='advertiser__adverti_7e8ab5_idx'),
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['status', 'start_date', 'end_date'], name='advertiser__status_b9c35c_idx'),
        ),
    ]
