# Generated by Django 6.0.4 on 2026-07-13 10:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertiser', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='media',
            field=models.ForeignKey(limit_choices_to={'status': ['admin_approved', 'fully_approved']}, on_delete=django.db.models.deletion.PROTECT, related_name='campaigns', to='advertiser.media'),
        ),
    ]
