# Generated by Django 6.0.4 on 2026-05-25 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertiser', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertiser',
            name='first_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='advertiser',
            name='last_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
