# Generated by Django 6.0.4 on 2026-07-13 10:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertiser', '0002_alter_campaign_media'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='media',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='campaigns', to='advertiser.media'),
        ),
    ]
