# Generated by Django 6.0.4 on 2026-05-27 09:24

import advertiser.models
import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertiser', '0002_advertiser_first_name_advertiser_last_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=180)),
                ('file', models.FileField(upload_to=advertiser.models.media_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp', 'mp4', 'mov', 'webm'])])),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video')], max_length=10)),
                ('duration_seconds', models.PositiveIntegerField(blank=True, help_text='Required for video. Duration the ad will play on screen.', null=True)),
                ('file_size_bytes', models.PositiveBigIntegerField(default=0, editable=False)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to=advertiser.models.thumbnail_upload_path)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=16)),
                ('rejection_reason', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('advertiser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_files', to='advertiser.advertiser')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_media', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'media',
                'indexes': [models.Index(fields=['advertiser', 'status'], name='advertiser__adverti_519a6f_idx'), models.Index(fields=['media_type'], name='advertiser__media_t_177127_idx'), models.Index(fields=['status'], name='advertiser__status_392294_idx')],
            },
        ),
    ]
