# Generated by Django 6.0.4 on 2026-05-28 00:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertiser', '0003_media'),
        ('device', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('daily_start_time', models.TimeField(default='06:00')),
                ('daily_end_time', models.TimeField(default='22:00')),
                ('budget', models.DecimalField(decimal_places=2, max_digits=12)),
                ('estimated_price', models.DecimalField(decimal_places=2, default=0, help_text='Calculated from billboard price_per_slot × slot count × campaign days.', max_digits=12)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_approval', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('active', 'Active'), ('paused', 'Paused'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=24)),
                ('rejection_reason', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('advertiser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='advertiser.advertiser')),
                ('media', models.ForeignKey(limit_choices_to={'status', 'approved'}, on_delete=django.db.models.deletion.PROTECT, related_name='campaigns', to='advertiser.media')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_campaigns', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CampaignSlot',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slots_per_day', models.PositiveIntegerField(default=1)),
                ('billboard', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='campaign_slots', to='device.billboard')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_slots', to='advertiser.campaign')),
            ],
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['advertiser', 'status'], name='advertiser__adverti_7e8ab5_idx'),
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['status', 'start_date', 'end_date'], name='advertiser__status_b9c35c_idx'),
        ),
        migrations.AddIndex(
            model_name='campaignslot',
            index=models.Index(fields=['campaign'], name='advertiser__campaig_486350_idx'),
        ),
        migrations.AddIndex(
            model_name='campaignslot',
            index=models.Index(fields=['billboard'], name='advertiser__billboa_0a2e5a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='campaignslot',
            unique_together={('campaign', 'billboard')},
        ),
    ]
