# Generated by Django 6.0.4 on 2026-07-16 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertiser', '0004_alter_campaign_end_date_alter_campaign_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='dates_confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='duration_days',
            field=models.PositiveSmallIntegerField(default=1, help_text='How many days the campaign runs. Real calendar dates are chosen after approval.'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending_admin_review', 'Pending Admin Review'), ('pending_manager_review', 'Pending Manager Review'), ('approved', 'Approved'), ('approval_expired', 'Approval Expired'), ('rejected', 'Rejected'), ('active', 'Active'), ('paused', 'Paused'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=24),
        ),
    ]
