# Generated by Django 6.0.4 on 2026-05-29 00:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertiser', '0004_campaign_campaignslot_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='media',
            field=models.ForeignKey(limit_choices_to={'status': 'approved'}, on_delete=django.db.models.deletion.PROTECT, related_name='campaigns', to='advertiser.media'),
        ),
    ]
