# Generated by Django 6.0.4 on 2026-08-01 03:03

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertiser', '0005_campaign_approved_at_campaign_dates_confirmed_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertiser',
            name='first_name',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='advertiser',
            name='last_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='actual_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='admanager_split_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='admin_split_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='budget',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='duration_days',
            field=models.PositiveSmallIntegerField(default=1, help_text='How many days the campaign runs. Real calendar dates are chosen after approval.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(90)]),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='estimated_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Calculated from billboard price_per_slot × slot count × campaign days.', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='campaignslot',
            name='slots_per_day',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(50)]),
        ),
        migrations.AlterField(
            model_name='media',
            name='duration_seconds',
            field=models.PositiveIntegerField(blank=True, help_text='Required for video. Duration the ad will play on screen.', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(15)]),
        ),
    ]
