# Generated by Django 6.0.4 on 2026-05-29 15:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertiser', '0005_alter_campaign_media'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='campaign',
            old_name='reviewed_at',
            new_name='admin_reviewed_at',
        ),
        migrations.RenameField(
            model_name='media',
            old_name='reviewed_at',
            new_name='admin_reviewed_at',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='reviewed_by',
        ),
        migrations.RemoveField(
            model_name='media',
            name='reviewed_by',
        ),
        migrations.AddField(
            model_name='campaign',
            name='admin_reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_campaigns_admin', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='campaign',
            name='manager_reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='manager_reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_campaigns_manager', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='media',
            name='admin_reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_media_admin', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='media',
            name='manager_reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='media',
            name='manager_reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_media_manager', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='media',
            field=models.ForeignKey(limit_choices_to={'status': 'admin_approved'}, on_delete=django.db.models.deletion.PROTECT, related_name='campaigns', to='advertiser.media'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending_admin_review', 'Pending Admin Review'), ('pending_manager_review', 'Pending Manager Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('active', 'Active'), ('paused', 'Paused'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=24),
        ),
        migrations.AlterField(
            model_name='media',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Review'), ('admin_approved', 'Admin Approved'), ('fully_approved', 'Fully Approved'), ('rejected', 'Rejected')], default='pending', max_length=16),
        ),
    ]
