# Generated by Django 6.0.4 on 2026-06-05 13:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertiser', '0006_rename_reviewed_at_campaign_admin_reviewed_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advertiser',
            options={},
        ),
        migrations.AddField(
            model_name='advertiser',
            name='verification_requested',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='advertiser',
            name='verification_requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='advertiser',
            index=models.Index(fields=['is_verified'], name='advertiser__is_veri_d57754_idx'),
        ),
        migrations.AddIndex(
            model_name='advertiser',
            index=models.Index(fields=['business_category'], name='advertiser__busines_2eb11f_idx'),
        ),
    ]
