# Generated by Django 6.0.4 on 2026-08-02 00:37

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertiser', '0006_alter_advertiser_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='actual_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='admanager_split_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='admin_split_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='budget',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='estimated_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Calculated from billboard price_per_slot × slot count × campaign days.', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
    ]
