# Generated by Django 6.0.4 on 2026-06-03 10:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertiser', '0006_rename_reviewed_at_campaign_admin_reviewed_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advertiser',
            options={},
        ),
        migrations.AddField(
            model_name='media',
            name='file_hash',
            field=models.CharField(blank=True, help_text='SHA-256 of the uploaded file. Used to detect duplicates.', max_length=64),
        ),
        migrations.AddConstraint(
            model_name='media',
            constraint=models.UniqueConstraint(fields=('advertiser', 'file_hash'), name='unique_media_per_advertiser'),
        ),
    ]
