# Generated by Django 6.0.4 on 2026-06-12 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advertiser', '0007_alter_advertiser_options_and_more'),
        ('advertiser', '0007_alter_advertiser_options_media_file_hash_and_more'),
    ]

    operations = [
    ]
