# Generated by Django 6.0.4 on 2026-08-14 06:59

import advertiser.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertiser', '0007_alter_campaign_actual_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='height',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='media',
            name='processed_file',
            field=models.FileField(blank=True, help_text='Transcoded/normalized version actually served to devices. Empty if the original already met spec.', null=True, upload_to=advertiser.models.media_upload_path),
        ),
        migrations.AddField(
            model_name='media',
            name='transcode_error',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='media',
            name='transcode_status',
            field=models.CharField(choices=[('pending', 'Not processed yet'), ('processing', 'Processing'), ('done', 'Ready for playback'), ('failed', 'Processing failed')], default='pending', help_text='Whether this file is verified safe to decode on billboard hardware.', max_length=12),
        ),
        migrations.AddField(
            model_name='media',
            name='video_codec',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='media',
            name='width',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='daily_end_time',
            field=models.TimeField(default=datetime.time(22, 0)),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='daily_start_time',
            field=models.TimeField(default=datetime.time(6, 0)),
        ),
    ]
