# Generated by Django 6.0.4 on 2026-06-14 17:03

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertiser', '0008_merge_20260612_2023'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='actual_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='campaign',
            name='admanager_split_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='campaign',
            name='admin_split_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
    ]
