# Generated by Django 6.0.4 on 2026-08-23 17:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertiser', '0008_media_height_media_processed_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='duration_seconds',
            field=models.PositiveIntegerField(blank=True, help_text='Required for video. Duration the ad will play on screen.', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(90)]),
        ),
    ]
